name: "monorepo test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # testing on whole Babel monorepo
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta

      - uses: actions/checkout@v2-beta
        with:
          repository: babel/babel
          path: babel

      - uses: ./
        with:
          root: babel
